ALTER TYPE "CreditLedgerType" ADD VALUE IF NOT EXISTS 'PROMO_REDEMPTION';

CREATE TYPE "PromoCodeScope" AS ENUM ('DEPLOY_DISCOUNT', 'CREDIT_BALANCE');

ALTER TABLE "PromoCode"
ADD COLUMN "scope" "PromoCodeScope" NOT NULL DEFAULT 'DEPLOY_DISCOUNT';

ALTER TABLE "PromoRedemption"
ADD COLUMN "creditedBalance" INTEGER NOT NULL DEFAULT 0;
